export const URL_NOT_FOUND = 'URL Not Found';
export const NAME_REQUIRED = 'The field name is required';
export const ID_REQUIRED = 'ID is required';
export const COUNTRY_CREATED_MESSAGE = 'Country Created Successfully';
export const MONGO_SERVER_ERROR = 'MongoServerError';
export const INTERNAL_SERVER_ERROR = 'Internal Server Error';
export const MONGOOSE_DUPLICATE_ERROR_CODE = 11000;
export const SUCCESS_MESSAGE = 'success';
export const COUNTRY_NOT_FOUND = 'Country not found';
